### ISSUE TITLE
invoke pdb.py as a script

### ISSUE THREAD

**Issue by autosquid** [spiside/pdb-tutorial#2]
It would be helpful to introduce the way to invoke pdb.py as a script:

```
python -m pdb myscript.py
```

**Comment by spiside** [comment]
Hey @autosquid! At the end of the tutorial, you'll notice a note that contains the instructions to invoke the pdb module. You'll find it [here](https://github.com/spiside/pdb-tutorial/blame/3c15d2907d378b354cbacb1906002cf5d6e1a8b8/README.md#L645).
