### ISSUE TITLE
Potential improvements to pdb-tutorial

### ISSUE THREAD

**Issue by alphaCTzo7G** [spiside/pdb-tutorial#5]
Thanks for this great tutorial. This was very helpful in understanding how to use PDB.

 I noticed a few issues, so I thought I could help improve this further

 1. On line 435, it says we should set a break point on line 35, but on line 436, it says the breakpoint is actually on line 32

 `(Pdb) b 35
 Breakpoint 1 at /Users/Development/pdb-tutorial/dicegame/runner.py(32)run()
 (Pdb) c`

 Perhaps this is a typo.

 2. I also noticed a few typos and mismatches in README.md, which I corrected here

 3. As far as suggestions for improvement, perhaps some information about `bt`, `u`, `d` can be included
     1. https://www.youtube.com/watch?v=2FftatTS3jc
     2. https://pymotw.com/2/pdb/

**Comment by spiside** [comment]
Closed due to #6
